### ISSUE TITLE
Mega Embeds

### ISSUE THREAD

**Issue by 3li0** [marcomontalbano/video-to-markdown#49]
Would be nice to see this working for mega embedding as well:

```
[![Titanic with a cat](https://i.ytimg.com/vi/kEPfM3jSoBw/maxresdefault.jpg)](https://mega.nz/embed/ANdknJKb#97QHxGirG0TcgiyzE40WqMTEFFjAln0sl7oJlFFhHpw "Titanic with a cat")
```

**Comment by marcomontalbano** [comment]
Hi @3li0, thanks for the request. Unfortunately is not possible to get the video thumbnail from Mega. They don't have a public API and they have an amazing cryptographic layer on the client app so that is not possible to grab information from there!
I'll let you know as you as this will be implemented in the future.
