### ISSUE TITLE
Unlimited bandwith

### ISSUE THREAD

**Issue by catdroutcode** [marcomontalbano/video-to-markdown#52]
Switch to [Cloudflare Pages](https://pages.cloudflare.com/) they have unlimited bandwith for free

**Comment by marcomontalbano** [comment]
Hi @catdroutcode , thanks a lot for the suggestion. I'll take a look at that! At the moment I'm on Netlify as hosting solution and I don't have an high bandwidth usage.
Usually the issue is with Cloudinary, since sometimes happen that websites with high bandwidth usage are pointing to images hosted by my Cloudinary account.

**Comment by catdroutcode** [comment]
You could code a cloudflare workers to handle images with Workers KV

**Comment by catdroutcode** [comment]
👍
