### ISSUE TITLE
Add API endpoints

### ISSUE THREAD

**Issue by Snailedlt** [marcomontalbano/video-to-markdown#59]
Any chance we could get some API endpoints? This opens up for integrating with video-to-markdown

Would be nice if we could for example visit 
https://video-to-markdown.marcomontalbano.com/api?url="https://www.youtube.com/watch?v=aqz-KE-bpKQ"
or 
https://video-to-markdown.marcomontalbano.com/api?url="https://youtu.be/aqz-KE-bpKQ"
then get the preview image returned. That way you don't have to store the image either, you can just generate it on the fly :)

**Comment by Snailedlt** [comment]
Btw I made a solution for youtube and vimeo which generates the images on the fly, and without saving the images anywhere: https://github.com/Snailedlt/Markdown-Videos so you can use that as an example if needed

**Comment by marcomontalbano** [comment]
Hi @Snailedlt,
I started this project as experiment on Netlify Functions. At the beginning I was generating images on the fly but after a while I started receiving a huge increase of incoming traffic (more bandwidth usage and execution minutes), so I switched to Cloudinary. With Cloudinary you get the best image compression and cache since the image is generated once and stored.
At the moment I'm not planning to add a dedicated API endpoint, but I don't exclude the possibility in the future.
